data:
  data_path: "Data/images/all_data" 
  batch_size: 32

training:
  epoch_number: 25
  learning_rate: 0.00001
  
model:
  checkpoint_dir: "models/"
  checkpoint_name: "best_lightning_model-v2.ckpt"
  margin_value: 1.0
  architectural : "mobilenet_v3"
  


